version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Sree@123
      POSTGRES_USER: admin123
      POSTGRES_DB: postgresdb123

  app: 
    image: lounge-server
    ports:
      - "13000:8000"
